### ISSUE TITLE
guce

### ISSUE THREAD

**Issue by p1r473** [migueldemoura/ublock-umatrix-rulesets#10]
Hi,
I noticed I was getting blocked when trying to visit TechCrunch links
I found theres a redirect to `guce.*.com` which is blocked (* any of the below domains:)
```
aol.com
aol.ca
aol.co.uk
engadget.com
compuserve.com
isp.netscape.com
huffingtonpost.ca
huffingtonpost.co.uk
huffingtonpost.com.au
rivals.com
techcrunch.com
verizonmedia.com
yahoo.com
```

I found this:
as per 
https://github.com/StevenBlack/hosts/issues/1370
https://github.com/lightswitch05/hosts/issues/188

Blocking guce breaks all sites owned by Verizon Media:
AOL
Autoblog
BUILD
Built By Girls
Engadget
Flurry
HuffPost
MAKERS
Rivals
RYOT
TechCrunch
Yahoo!

I would reconsider if you want to break all of the above.

**Comment by migueldemoura** [comment]
Hi @p1r473, I believe I moved all of them to the "breaking" list with https://github.com/migueldemoura/ublock-umatrix-rulesets/commit/e836487f60b91383ab1038b47fa221c281a99b27. Did I miss any? Do you think it's still not reasonable to have them in that "breaking" list?

**Comment by p1r473** [comment]
Sorry I didnt realize it was om breaking list
