### ISSUE TITLE
ae01.alicdn.com

### ISSUE THREAD

**Issue by p1r473** [migueldemoura/ublock-umatrix-rulesets#12]
This is an AliExpress Content Delivery Network (CDN)
This serves AliExpress images
I believe this is a false positive
![image](https://user-images.githubusercontent.com/9235633/129073786-8f019c0f-87b9-4f80-8279-e57ca54c54c0.png)

**Comment by migueldemoura** [comment]
Fixed with https://github.com/migueldemoura/ublock-umatrix-rulesets/commit/1fe7db910f538ad9e2679e39fb8f17adb7cdb661, thanks again!
