### ISSUE TITLE
dts.podtrac.com

### ISSUE THREAD

**Issue by p1r473** [migueldemoura/ublock-umatrix-rulesets#17]
This domain is used for downloading podcasts
This is non malicious

**Comment by migueldemoura** [comment]
Thanks for the report. This is used for podcast analytics, but sometimes it's the only link you have to fetch a podcast, hence why I put it in the "breaking" list and not the main one. I think it's acceptable to leave it there, what do you think?

**Comment by p1r473** [comment]
It is breaking the ability to download episodes on my android podcast app PocketCasts. I had to whitelist to download an episode.
