### ISSUE TITLE
Graph.facebook.com

### ISSUE THREAD

**Issue by p1r473** [migueldemoura/ublock-umatrix-rulesets#2]
Blocking this  domain breaks Facebook Groups on mobile.

**Comment by migueldemoura** [comment]
Moved the host to https://github.com/migueldemoura/ublock-umatrix-rulesets/blob/master/Hosts/ads-tracking-breaking so it isn't on the main list anymore. Thanks!

**Comment by p1r473** [comment]
So that ads-tracking-breaking list breaks things?

**Comment by migueldemoura** [comment]
It will break some use cases, yes.
