### ISSUE TITLE
^www.$domain

### ISSUE THREAD

**Issue by spirillen** [migueldemoura/ublock-umatrix-rulesets#20]
Hi @migueldemoura as I just added your list to my own uBlock list I spotted you have kept the `^www.` and I come to think is this was a honest homer or there was a specific reason to this?

https://github.com/migueldemoura/ublock-umatrix-rulesets/blob/7ed375350dd2e65d3c2728045547ea664caf13fb/uBlock/list#L81-L92

**Comment by migueldemoura** [comment]
Removed the annoyances from that file, indirectly addressing this issue - https://github.com/migueldemoura/ublock-umatrix-rulesets/commit/338ff6152bd4a8fa61427389798c516d6f81ebde. I don't think these are particularly useful for a general audience, so no point in keeping them here.

I'm also planning on "upstreaming" the remaining filters from that file to EasyList to focus on pure host detection which is what I'm most interested in and have written tooling for.

**Comment by spirillen** [comment]
> to focus on pure host detection which is what I'm most interested in...

hosts specific or 20 years more modern hosted DNS RPZ zones?

>  and have written tooling for...

Trying to look over your shoulder here... what can these tools do, beside monitoring the huge lists from the readme? is it some scripts that might evolve to report to the https://mypdns.org/my-privacy-dns/matrix as well.

---------------

Allow me to share a vision of mine:
That is all of us lists maintainer could figure out to have one "forum" for where we shared all our collected knowledge for categorizing, classifications severity in blacklisting or not etc. These information's should then end up to be extract-able ACTIVE data based on a personal opinion, it should not be a `one ring rule them all` but a `one ring knows it all` - One library for shared knowledge.

As it is today there are 1000's of projects and equally number is issue/reporting systems and 90% of that is the same...

The idea have a note here: https://mypdns.org/infrastructure/matrix-rocks/www.matrix.rocks as it is involving a few other projects.

What is your thought on a project like that?

**Comment by migueldemoura** [comment]
> Trying to look over your shoulder here... what can these tools do, beside monitoring the huge lists from the readme? is it some scripts that might evolve to report to the https://mypdns.org/my-privacy-dns/matrix as well.

Nothing fancy, just crawling the monitored websites, collecting all requests and applying some basic heuristics to flag domains that fit the criteria for these lists. There is prior work around this.

>The idea have a note here: https://mypdns.org/infrastructure/matrix-rocks/www.matrix.rocks as it is involving a few other projects.
>
> What is your thought on a project like that?

I will take a look, but I'm generally keen on proposals involving sharing of the data that is collected by all the projects to avoid duplication of work.
