### ISSUE TITLE
b.cdnst.net breaks speedtest.net

### ISSUE THREAD

**Issue by p1r473** [migueldemoura/ublock-umatrix-rulesets#21]
b.cdnst.net breaks speedtest.net
Also the only list out of my 500 lists that blocks this domain.. think its a false positive.
![image](https://user-images.githubusercontent.com/9235633/143614843-24801ef4-e730-4d19-9834-8230b702642d.png)

**Comment by migueldemoura** [comment]
It's indeed a false positive. Thanks for reporting, fixed with https://github.com/migueldemoura/ublock-umatrix-rulesets/commit/3a74c015217f8f745c9496113c93617ef16d879a.
