### ISSUE TITLE
public-ubiservices.ubi.com

### ISSUE THREAD

**Issue by p1r473** [migueldemoura/ublock-umatrix-rulesets#22]
Breaks Ubisoft Connect/Uplay game launcher
![image](https://user-images.githubusercontent.com/9235633/158893733-6aafde57-9d75-4991-b15c-d54aabf2092a.png)
This isnt a malicious domain

**Comment by migueldemoura** [comment]
Thanks, fixed with https://github.com/migueldemoura/ublock-umatrix-rulesets/commit/2423b74e6c58dee56630ecd15ef7f79d085b53b1.
