### ISSUE TITLE
CNet CDN cdn.cnetcontent.com

### ISSUE THREAD

**Issue by p1r473** [migueldemoura/ublock-umatrix-rulesets#23]
CNet CDN. does it actually host ads?
It blocked this for me, so it does host some non-ad content
https://cdn.cnetcontent.com/syndication/feeds/wd/inline-content/DF/DA5189F0BE49216D4F6304D4A173542EE85BC787_PRODUCTBRIEFWDGOLDHDD_source.PDF

**Comment by migueldemoura** [comment]
Looks like a false positive. I added it many years ago, and I don't have recent hits on from my crawler. Removed with https://github.com/migueldemoura/ublock-umatrix-rulesets/commit/2d488f4bd1b0c1633361dc626cc8835fb375dd30, thanks a bunch!
