### ISSUE TITLE
app.gitbook.com

### ISSUE THREAD

**Issue by sr093906** [migueldemoura/ublock-umatrix-rulesets#24]
sign-in/sign up page of Gitbook

in https://github.com/migueldemoura/ublock-umatrix-rulesets/blob/master/Hosts/ads-tracking

**Comment by migueldemoura** [comment]
Fixed in https://github.com/migueldemoura/ublock-umatrix-rulesets/commit/1705e2ea547a332cac29b268ee21288207ce6c7c.
