### ISSUE TITLE
platform.twitter.com

### ISSUE THREAD

**Issue by p1r473** [migueldemoura/ublock-umatrix-rulesets#3]
This domain breaks some tweets embedded in articles in Google News app on Android

**Comment by migueldemoura** [comment]
That host is already in https://github.com/migueldemoura/ublock-umatrix-rulesets/blob/master/Hosts/ads-tracking-breaking, which contains hosts that may break some use cases. You can add it to your blocker's exclusion list or in last resort unsubscribe from that specific list. Thanks!

**Comment by p1r473** [comment]
Thanks!
Just reporting it anyway, just in case.

**Comment by migueldemoura** [comment]
Keep them coming! 👍
