### ISSUE TITLE
2mdn.ne

### ISSUE THREAD

**Issue by rdsu-pt** [migueldemoura/ublock-umatrix-rulesets#4]
I saw you have this host on your list:
2mdn.ne
s0.2mdn.ne

Is this right, or should be 2mdn.ne**t**?

**Comment by migueldemoura** [comment]
It should have the `.net` tld, that's what I get for delaying adding a basic CI check. I've fixed it with https://github.com/migueldemoura/ublock-umatrix-rulesets/commit/422b9c1496597fe41fc53fc6c31a63d21557b363. Thanks!
