### ISSUE TITLE
wired.com: can't play videos

### ISSUE THREAD

**Issue by rdsu-pt** [migueldemoura/ublock-umatrix-rulesets#5]
With your hosts list the videos at wired.com doesn't work:
https://www.wired.com/video/watch/wired-news-and-science-er-doctor-explains-how-theyre-handling-covid-19

**Comment by migueldemoura** [comment]
Thanks for another report! I've fixed with https://github.com/migueldemoura/ublock-umatrix-rulesets/commit/0a370beac9ea140005d207db5eb2c26bd5b509a4. Please let me know if the issue persists.
