### ISSUE TITLE
abebooks.com www.abebooks.com

### ISSUE THREAD

**Issue by p1r473** [migueldemoura/ublock-umatrix-rulesets#6]
Hi,
abebooks.com www.abebooks.com
These domains that are being blocked is an online book store. I believe it may be a False Positive.

![image](https://user-images.githubusercontent.com/9235633/78682837-817f2680-78bc-11ea-84d4-183693ac8f6d.png)

**Comment by migueldemoura** [comment]
Removed those two with https://github.com/migueldemoura/ublock-umatrix-rulesets/commit/7b3ba0e2a8580f5df849ffd419fc185685de9411, definitely shouldn't be there given the commit I introduced them in. Thanks again!
