### ISSUE TITLE
www.arcgis.com arcgis.com

### ISSUE THREAD

**Issue by p1r473** [migueldemoura/ublock-umatrix-rulesets#7]
Hi, this domain is required for Johns Hopkins covid
It is not a malicious domain
![image](https://user-images.githubusercontent.com/9235633/96938347-1f70c200-1498-11eb-9ac7-83c0ea060201.png)

**Comment by migueldemoura** [comment]
Removed those and the other subdomains with fab5d9b and added them to the allowed hosts in my crawler. Thanks!
