### ISSUE TITLE
False Positive ir.ebaystatic.com

### ISSUE THREAD

**Issue by p1r473** [migueldemoura/ublock-umatrix-rulesets#8]
Blocking this domain breaks the layout on ebay.co.uk for me.

**Comment by migueldemoura** [comment]
Noticed that one as well and fixed it a few days ago with https://github.com/migueldemoura/ublock-umatrix-rulesets/commit/d11cb40088dcbd88e5d1500f2faa66f9615a69ff. Also adjusted the heuristic that flagged it and added the host to the allow list. Thanks again!
