### ISSUE TITLE
guce.yahoo.com

### ISSUE THREAD

**Issue by p1r473** [migueldemoura/ublock-umatrix-rulesets#9]
Hi,
This domain redirects to a.finance.yahoo.com
However when you Google a stock, the Yahoo finance link leads to guce.yahoo.com
 Guce is a server that handles the consent mechanism related to General Data Protection Regulation (GDPR)
https://www.wipersoft.com/what-is-guce-yahoo-com/

**Comment by migueldemoura** [comment]
I'm aware of this general issue. There are a few of these "guce" endpoints in the main list:
```
guce.advertising.com
guce.engadget.com
guce.huffpost.com
guce.techcrunch.com
guce.yahoo.com
```
I think the best course of action is to move them to the "breaking" list.

**Comment by migueldemoura** [comment]
Moved with e836487.
